// Work-visa knowledge base. Figures were checked in September 2026 against the
// official sources linked next to them; immigration rules change often, so the
// report always tells users to confirm on the official site before applying.

export const AS_OF = '2026-09';

export const COUNTRIES = {
  DE: {
    name: 'Germany', fa: 'آلمان',
    englishOk: 'tech', mainLanguage: 'German',
    shortage: ['software', 'data', 'devops', 'security', 'qa', 'engineering', 'healthcare'],
    official: 'https://www.make-it-in-germany.com/en/',
    recognition: { name: 'anabin / ZAB degree recognition', url: 'https://anabin.kmk.org/' },
    routes: [
      { name: 'EU Blue Card', needsDegree: true, summary: 'Recognised degree + job offer at or above the salary threshold. Permanent residence after 21–27 months.', threshold: { amount: 50700, currency: 'EUR', period: 'year' }, reduced: { amount: 45934.2, currency: 'EUR', period: 'year', note: 'shortage occupations, IT specialists and graduates of the last 3 years' }, url: 'https://www.make-it-in-germany.com/en/visa-residence/types/eu-blue-card' },
      { name: 'IT specialist without a degree', summary: 'At least 3 years of IT experience in the last 7 years and a job offer at the reduced Blue Card salary.', families: ['software', 'data', 'devops', 'security', 'qa'], url: 'https://www.make-it-in-germany.com/en/visa-residence/types/it-specialists' },
      { name: 'Opportunity Card (Chancenkarte)', summary: 'Points-based job-seeker permit for up to 1 year; you may work part-time (20 h/week) and do trial jobs while searching. Needs a recognised qualification and German A1 or English B2.', url: 'https://www.make-it-in-germany.com/en/visa-residence/types/job-search-opportunity-card' },
      { name: 'Skilled worker visa (§18a/§18b)', summary: 'For recognised degree or vocational qualification holders with a matching job offer; no fixed salary threshold under 45.', url: 'https://www.make-it-in-germany.com/en/visa-residence/types/work-qualified-professionals' },
    ],
    cv: 'Tabular CV (Lebenslauf), 2 pages, photo optional, exact month/year dates, add language levels (CEFR). A short Anschreiben (cover letter) is still expected by many employers.',
    notes: ['German at B1+ multiplies non-tech options; many tech teams work in English.', 'Book the embassy visa appointment early: wait times can be long.'],
  },
  NL: {
    name: 'Netherlands', fa: 'هلند',
    englishOk: 'wide', mainLanguage: 'Dutch',
    shortage: ['software', 'data', 'devops', 'security', 'engineering'],
    official: 'https://ind.nl/en/work',
    recognition: { name: 'Nuffic / IDW credential evaluation', url: 'https://www.idw.nl/en/' },
    routes: [
      { name: 'Highly Skilled Migrant (kennismigrant)', summary: 'Employer must be an IND recognised sponsor. Fast (≈2–4 weeks). No degree required.', threshold: { amount: 5942, currency: 'EUR', period: 'month', note: 'age 30+' }, reduced: { amount: 4357, currency: 'EUR', period: 'month', note: 'under 30' }, url: 'https://ind.nl/en/residence-permits/work/highly-skilled-migrant' },
      { name: 'EU Blue Card (NL)', needsDegree: true, summary: 'Bachelor degree + salary threshold; any employer (sponsor recognition not required).', url: 'https://ind.nl/en/residence-permits/work/european-blue-card' },
      { name: 'Orientation year (zoekjaar)', summary: 'For graduates of top-200 universities worldwide within 3 years of graduation; then the reduced €3,122/month threshold applies.', url: 'https://ind.nl/en/residence-permits/work/residence-permit-for-orientation-year' },
    ],
    cv: 'Concise 1–2 page CV, no photo needed, direct tone; mention right-to-work needs up front.',
    notes: ['Only apply to employers on the IND public register of recognised sponsors for the kennismigrant route.', 'Salary thresholds exclude the 8% holiday allowance.'],
  },
  GB: {
    name: 'United Kingdom', fa: 'انگلستان',
    englishOk: 'native', mainLanguage: 'English',
    shortage: ['software', 'data', 'devops', 'security', 'engineering', 'healthcare'],
    official: 'https://www.gov.uk/browse/visas-immigration/work-visas',
    recognition: { name: 'UK ENIC statement of comparability', url: 'https://www.enic.org.uk/' },
    routes: [
      { name: 'Skilled Worker visa', summary: 'Job offer from a Home Office licensed sponsor at RQF level 6 (degree level) and English at the required CEFR level. Salary: the higher of the general threshold and the occupation going rate.', threshold: { amount: 41700, currency: 'GBP', period: 'year' }, reduced: { amount: 33400, currency: 'GBP', period: 'year', note: 'new entrants (e.g. under 26 or recent graduates) — check eligibility' }, url: 'https://www.gov.uk/skilled-worker-visa' },
      { name: 'Global Talent visa', summary: 'No job offer needed; endorsement for leaders or potential leaders in digital technology, science, arts.', url: 'https://www.gov.uk/global-talent' },
      { name: 'High Potential Individual', summary: 'For graduates of top global universities (list published yearly); no job offer needed.', url: 'https://www.gov.uk/high-potential-individual-visa' },
    ],
    cv: '2-page CV, no photo, no date of birth; achievements with numbers. Cover letters are short.',
    notes: ['Check the employer on the register of licensed sponsors before investing time.'],
  },
  IE: {
    name: 'Ireland', fa: 'ایرلند',
    englishOk: 'native', mainLanguage: 'English',
    shortage: ['software', 'data', 'devops', 'security', 'engineering', 'healthcare', 'finance'],
    official: 'https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/',
    recognition: { name: 'QQI qualification recognition', url: 'https://www.qqi.ie/' },
    routes: [
      { name: 'Critical Skills Employment Permit', summary: 'For roles on the Critical Skills Occupations List (most tech/engineering roles). Family can join immediately; path to Stamp 4 after 2 years.', threshold: { amount: 40904, currency: 'EUR', period: 'year' }, reduced: { amount: 36848, currency: 'EUR', period: 'year', note: 'graduates within the last 12 months' }, url: 'https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/permit-types/critical-skills-employment-permit/' },
      { name: 'General Employment Permit', summary: 'For other occupations not on the ineligible list; labour market needs test usually required.', url: 'https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/permit-types/general-employment-permit/' },
    ],
    cv: '2-page CV, no photo. Dublin tech market is English-only.',
    notes: ['Thresholds rise gradually each year under the 2026 roadmap.'],
  },
  SE: {
    name: 'Sweden', fa: 'سوئد',
    englishOk: 'wide', mainLanguage: 'Swedish',
    shortage: ['software', 'data', 'devops', 'engineering', 'healthcare'],
    official: 'https://www.migrationsverket.se/en/you-want-to-apply/work.html',
    recognition: { name: 'UHR degree evaluation', url: 'https://www.uhr.se/en/start/recognition-of-foreign-qualifications/' },
    routes: [
      { name: 'Work permit', summary: 'Job offer with salary ≥ 90% of the Swedish median wage and terms matching collective agreements. Path to permanent residence after 4 years.', threshold: { amount: 34470, currency: 'SEK', period: 'month' }, url: 'https://www.migrationsverket.se/en/you-want-to-apply/work/employee-or-self-employed/employees.html' },
      { name: 'EU Blue Card (SE)', needsDegree: true, summary: 'Higher salary threshold; faster family and EU mobility benefits.', url: 'https://www.migrationsverket.se/en/you-want-to-apply/work/eu-blue-card.html' },
      { name: 'Residence permit to look for work', summary: 'For people with an advanced (master+) degree: up to 9 months to find a job.', url: 'https://www.migrationsverket.se/en/you-want-to-apply/work/looking-for-work-or-starting-a-business.html' },
    ],
    cv: 'Clean 1–2 page CV, informal tone, personal letter (personligt brev) valued.',
    notes: ['Certified employers get work permits decided in weeks rather than months.'],
  },
  FI: {
    name: 'Finland', fa: 'فنلاند',
    englishOk: 'tech', mainLanguage: 'Finnish',
    shortage: ['software', 'data', 'devops', 'engineering', 'healthcare'],
    official: 'https://migri.fi/en/working-in-finland',
    recognition: { name: 'Finnish National Agency for Education', url: 'https://www.oph.fi/en/services/recognition-and-international-comparability-qualifications' },
    routes: [
      { name: 'Specialist residence permit', summary: 'Higher-education level expert role with a salary around the national median or above; eligible for the 14-day fast track.', url: 'https://migri.fi/en/specialist' },
      { name: 'EU Blue Card (FI)', needsDegree: true, summary: 'Degree + salary threshold; fast track available.', url: 'https://migri.fi/en/eu-blue-card' },
    ],
    cv: 'Short CV with a LinkedIn link; Finnish employers value modesty and concrete facts.',
    notes: ['Work in Finland (official) runs talent programmes that help with relocation.'],
  },
  DK: {
    name: 'Denmark', fa: 'دانمارک',
    englishOk: 'wide', mainLanguage: 'Danish',
    shortage: ['software', 'data', 'devops', 'engineering', 'healthcare'],
    official: 'https://www.nyidanmark.dk/en-GB/You-want-to-apply/Work',
    recognition: { name: 'Danish Agency for Higher Education (recognition)', url: 'https://ufm.dk/en/education/recognition-and-transparency' },
    routes: [
      { name: 'Pay Limit Scheme', summary: 'Any job with an annual salary above the pay limit (indexed yearly).', url: 'https://www.nyidanmark.dk/en-GB/You-want-to-apply/Work/Pay-limit-scheme' },
      { name: 'Positive List', summary: 'Jobs on the positive lists for people with higher education or skilled workers.', url: 'https://www.nyidanmark.dk/en-GB/You-want-to-apply/Work/Positive-List-for-people-with-a-higher-education' },
      { name: 'Fast-track scheme', summary: 'Certified employers can onboard quickly.', url: 'https://www.nyidanmark.dk/en-GB/You-want-to-apply/Work/Fast-track-scheme' },
    ],
    cv: '1–2 page CV plus motivated application letter.',
    notes: [],
  },
  AT: {
    name: 'Austria', fa: 'اتریش',
    englishOk: 'tech', mainLanguage: 'German',
    shortage: ['software', 'data', 'devops', 'engineering', 'healthcare'],
    official: 'https://www.migration.gv.at/en/',
    recognition: { name: 'ENIC NARIC Austria', url: 'https://www.aais.at/' },
    routes: [
      { name: 'Red-White-Red Card (skilled workers in shortage occupations)', summary: 'Points-based (qualification, experience, language, age) with a job offer.', url: 'https://www.migration.gv.at/en/types-of-immigration/permanent-immigration/skilled-workers-in-shortage-occupations/' },
      { name: 'EU Blue Card (AT)', needsDegree: true, summary: 'Degree + salary threshold.', url: 'https://www.migration.gv.at/en/types-of-immigration/permanent-immigration/eu-blue-card/' },
    ],
    cv: 'Similar to Germany: tabular CV and cover letter.',
    notes: [],
  },
  PT: {
    name: 'Portugal', fa: 'پرتغال',
    englishOk: 'tech', mainLanguage: 'Portuguese',
    shortage: ['software', 'data', 'devops'],
    official: 'https://vistos.mne.gov.pt/en/',
    recognition: { name: 'DGES degree recognition', url: 'https://www.dges.gov.pt/en' },
    routes: [
      { name: 'Tech Visa', summary: 'Fast-tracked visa for qualified staff hired by companies certified under the Tech Visa programme.', url: 'https://techvisa.iapmei.pt/' },
      { name: 'Highly qualified activity visa', summary: 'For highly qualified roles with an employment contract.', url: 'https://vistos.mne.gov.pt/en/national-visas/general-information/type-of-visa' },
      { name: 'Digital nomad visa', summary: 'For remote workers/freelancers with income ≥ 4× the Portuguese minimum wage from foreign clients.', url: 'https://vistos.mne.gov.pt/en/national-visas/general-information/type-of-visa' },
    ],
    cv: 'Europass format is common; English is fine in tech.',
    notes: ['Lower salaries than northern Europe but lower cost of living and a digital-nomad route for freelancers.'],
  },
  ES: {
    name: 'Spain', fa: 'اسپانیا',
    englishOk: 'tech', mainLanguage: 'Spanish',
    shortage: ['software', 'data', 'devops', 'healthcare'],
    official: 'https://www.inclusion.gob.es/web/unidadgrandesempresas',
    recognition: { name: 'Homologación (Ministry of Universities)', url: 'https://www.universidades.gob.es/' },
    routes: [
      { name: 'Highly Qualified Professional (UGE)', summary: 'Fast track (≈20 days) for qualified professionals hired by larger or strategic companies.', url: 'https://www.inclusion.gob.es/web/unidadgrandesempresas' },
      { name: 'Digital nomad visa', summary: 'For remote workers/freelancers earning ≥ 200% of the Spanish minimum wage from foreign companies.', url: 'https://www.exteriores.gob.es/' },
      { name: 'EU Blue Card (ES)', needsDegree: true, summary: 'Degree + salary threshold.', url: 'https://www.inclusion.gob.es/web/unidadgrandesempresas' },
    ],
    cv: 'Europass or clean 2-page CV; Spanish helps a lot outside tech.',
    notes: [],
  },
  EE: {
    name: 'Estonia', fa: 'استونی',
    englishOk: 'tech', mainLanguage: 'Estonian',
    shortage: ['software', 'data', 'devops', 'security'],
    official: 'https://www.workinestonia.com/',
    recognition: { name: 'ENIC/NARIC Estonia', url: 'https://harno.ee/en' },
    routes: [
      { name: 'Top specialist / EU Blue Card', summary: 'Salary at or above 1.5× the Estonian average wage for top specialists.', url: 'https://www.politsei.ee/en/instructions/residence-permit-for-employment' },
      { name: 'Startup visa', summary: 'For founders and staff of startups approved by the Startup Committee.', url: 'https://startupestonia.ee/startup-visa/' },
      { name: 'Digital nomad visa', summary: 'For remote workers with foreign employers/clients and a minimum monthly income.', url: 'https://www.politsei.ee/en/instructions/applying-for-a-visa/digital-nomad-visa' },
    ],
    cv: 'Short CV, English is standard in startups.',
    notes: ['Small but very international tech scene (Wise, Bolt, Pipedrive).'],
  },
  PL: {
    name: 'Poland', fa: 'لهستان',
    englishOk: 'tech', mainLanguage: 'Polish',
    shortage: ['software', 'data', 'devops', 'qa'],
    official: 'https://www.gov.pl/web/udsc-en',
    recognition: { name: 'NAWA recognition', url: 'https://nawa.gov.pl/en/recognition' },
    routes: [
      { name: 'Work permit (type A) + national visa', summary: 'Employer obtains the permit; relatively accessible, many international tech hubs (Warsaw, Kraków, Wrocław).', url: 'https://www.gov.pl/web/udsc-en' },
      { name: 'EU Blue Card (PL)', needsDegree: true, summary: 'Degree + salary threshold; gives EU mobility after 12 months.', url: 'https://www.gov.pl/web/udsc-en' },
    ],
    cv: 'Europass-style CV; add the GDPR consent clause at the bottom (required by many Polish employers).',
    notes: ['Good stepping stone: after 12 months on a Blue Card you can move to another EU country more easily.'],
  },
  CA: {
    name: 'Canada', fa: 'کانادا',
    englishOk: 'native', mainLanguage: 'English/French',
    shortage: ['software', 'data', 'devops', 'engineering', 'healthcare', 'education'],
    official: 'https://www.canada.ca/en/immigration-refugees-citizenship/services/immigrate-canada/express-entry.html',
    recognition: { name: 'Educational Credential Assessment (WES etc.)', url: 'https://www.canada.ca/en/immigration-refugees-citizenship/services/immigrate-canada/express-entry/documents/education-assessed.html' },
    routes: [
      { name: 'Express Entry (permanent residence)', summary: 'Points-based (CRS): age, education, language (IELTS/CELPIP/TEF), experience. Category draws favour French, healthcare, STEM and trades. Job-offer points were removed in 2025, so a job is not required.', url: 'https://www.canada.ca/en/immigration-refugees-citizenship/services/immigrate-canada/express-entry.html' },
      { name: 'Provincial Nominee Programs', summary: 'Provinces nominate candidates in their in-demand occupations (tech draws in BC and Ontario).', url: 'https://www.canada.ca/en/immigration-refugees-citizenship/services/immigrate-canada/provincial-nominees.html' },
      { name: 'Global Talent Stream (work permit)', summary: 'Employers can hire in-demand tech workers with ~2-week processing.', url: 'https://www.canada.ca/en/employment-social-development/services/foreign-workers/global-talent.html' },
    ],
    cv: 'North-American résumé: 1–2 pages, no photo, no age/marital status, achievement bullets.',
    notes: ['Calculate your CRS score before paying for anything.'],
  },
  AU: {
    name: 'Australia', fa: 'استرالیا',
    englishOk: 'native', mainLanguage: 'English',
    shortage: ['software', 'data', 'devops', 'security', 'engineering', 'healthcare', 'education'],
    official: 'https://immi.homeaffairs.gov.au/',
    recognition: { name: 'Skills assessment (e.g. ACS for IT, Engineers Australia)', url: 'https://www.acs.org.au/msa.html' },
    routes: [
      { name: 'Skills in Demand visa (subclass 482)', summary: 'Employer-sponsored; Core Skills stream requires a salary above the Core Skills Income Threshold (indexed every July).', url: 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/skills-in-demand-482' },
      { name: 'Skilled Independent (subclass 189)', summary: 'Points-tested permanent visa, no sponsor needed; requires a positive skills assessment.', url: 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/skilled-independent-189' },
    ],
    cv: '2–3 page résumé, no photo; list referees.',
    notes: [],
  },
  NZ: {
    name: 'New Zealand', fa: 'نیوزیلند',
    englishOk: 'native', mainLanguage: 'English',
    shortage: ['software', 'data', 'devops', 'engineering', 'healthcare', 'education'],
    official: 'https://www.immigration.govt.nz/',
    recognition: { name: 'NZQA International Qualifications Assessment', url: 'https://www2.nzqa.govt.nz/international/' },
    routes: [
      { name: 'Accredited Employer Work Visa', summary: 'Job offer from an accredited employer at or above the median-wage requirement.', url: 'https://www.immigration.govt.nz/new-zealand-visas/visas/visa/accredited-employer-work-visa' },
      { name: 'Green List residence', summary: 'Some roles (many engineering, health and ICT) lead straight or quickly to residence.', url: 'https://www.immigration.govt.nz/new-zealand-visas/preparing-a-visa-application/working-in-nz/qualifications-for-work/green-list-occupations' },
    ],
    cv: '2–3 page CV, no photo.',
    notes: [],
  },
  AE: {
    name: 'United Arab Emirates', fa: 'امارات',
    englishOk: 'native', mainLanguage: 'Arabic/English',
    shortage: ['software', 'data', 'devops', 'security', 'engineering', 'healthcare', 'finance', 'sales', 'marketing'],
    official: 'https://u.ae/en/information-and-services/visa-and-emirates-id',
    recognition: { name: 'Degree attestation (MOFA)', url: 'https://www.mofa.gov.ae/en/services/attestation' },
    routes: [
      { name: 'Employer-sponsored work visa', summary: 'The employer handles the entry permit, residence visa and Emirates ID; fast (1–4 weeks). No income tax.', url: 'https://u.ae/en/information-and-services/visa-and-emirates-id/residence-visas/residence-visa-for-working-in-the-uae' },
      { name: 'Golden Visa (skilled professionals)', summary: '10-year visa for professionals with a bachelor degree and a high monthly salary (skill level 1–2).', url: 'https://u.ae/en/information-and-services/visa-and-emirates-id/residence-visas/golden-visa' },
      { name: 'Green Visa (freelancers / skilled)', summary: '5-year self-sponsored visa for freelancers and skilled employees meeting income/degree requirements.', url: 'https://u.ae/en/information-and-services/visa-and-emirates-id/residence-visas/green-visa' },
    ],
    cv: '2-page CV; a photo, nationality and visa status are commonly included.',
    notes: ['Visa approval for some nationalities can involve extra checks or temporary restrictions; ask the employer’s PRO early.', 'No permanent residence track; many use the UAE as a 2–3 year stepping stone.'],
  },
  US: {
    name: 'United States', fa: 'آمریکا',
    englishOk: 'native', mainLanguage: 'English',
    shortage: ['software', 'data', 'devops', 'security', 'engineering', 'healthcare'],
    official: 'https://www.uscis.gov/working-in-the-united-states',
    recognition: { name: 'Credential evaluation (NACES members)', url: 'https://www.naces.org/' },
    routes: [
      { name: 'H-1B', summary: 'Employer-sponsored, annual lottery. A $100,000 fee applies to many new petitions for workers outside the US since September 2025 — confirm current rules.', url: 'https://www.uscis.gov/working-in-the-united-states/h-1b-specialty-occupations' },
      { name: 'O-1', summary: 'For people with extraordinary ability (publications, awards, press, high salary).', url: 'https://www.uscis.gov/working-in-the-united-states/temporary-workers/o-1-visa-individuals-with-extraordinary-ability-or-achievement' },
      { name: 'EB-2 National Interest Waiver', summary: 'Self-petitioned green card for advanced-degree holders whose work has national importance.', url: 'https://www.uscis.gov/working-in-the-united-states/permanent-workers/employment-based-immigration-second-preference-eb-2' },
    ],
    cv: '1-page (junior) or 2-page résumé, no photo, no age.',
    notes: [],
  },
};

// Nationality-specific cautions. Kept factual and general; always verify.
export const NATIONALITY_NOTES = {
  IR: {
    blockedCountries: { US: 'Entry for Iranian nationals has been suspended by US presidential proclamation since June 2025 (with narrow exceptions). Check the current status on travel.state.gov before considering US roles.' },
    general: [
      'Visa processing for Iranian passport holders usually includes extra security screening — plan for 2–6 extra months.',
      'Embassy appointment queues in Tehran can be long; many applicants apply through consulates in Ankara, Istanbul, Yerevan or Dubai where accepted.',
      'Many international platforms (Upwork, Fiverr, PayPal, Stripe) do not serve users located in sanctioned countries; accounts that break their terms get closed and funds frozen. Use platforms and payment channels that officially support your country of residence.',
      'Get degree certificates translated and legalised early (Ministry of Science/Health + Foreign Affairs), it often takes weeks.',
    ],
    generalFa: [
      'روند ویزا برای دارندگان پاسپورت ایرانی معمولاً بررسی امنیتی بیشتری دارد؛ ۲ تا ۶ ماه زمان اضافه در نظر بگیرید.',
      'صف نوبت سفارت‌ها در تهران طولانی است؛ بسیاری از متقاضیان (در صورت پذیرش سفارت) از کنسولگری‌های آنکارا، استانبول، ایروان یا دبی اقدام می‌کنند.',
      'بسیاری از پلتفرم‌های بین‌المللی (Upwork، Fiverr، PayPal، Stripe) به کاربران ساکن کشورهای تحت تحریم سرویس نمی‌دهند و حساب‌های خلاف قوانینشان بسته و پولشان بلوکه می‌شود. از پلتفرم‌ها و روش‌های پرداختی استفاده کنید که رسماً کشور محل اقامت شما را پشتیبانی می‌کنند.',
      'ترجمه رسمی و تأیید مدارک تحصیلی (وزارت علوم/بهداشت و امور خارجه) را زود شروع کنید؛ معمولاً چند هفته طول می‌کشد.',
    ],
    blockedCountriesFa: { US: 'ورود اتباع ایران به آمریکا از ژوئن ۲۰۲۵ با فرمان ریاست‌جمهوری (جز استثناهای محدود) متوقف شده است. قبل از اپلای برای موقعیت‌های آمریکا وضعیت فعلی را در travel.state.gov بررسی کنید.' },
  },
};
